# Generated by Django 4.2.8 on 2023-12-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('displayName', models.CharField(max_length=36)),
                ('iconFileId', models.CharField(max_length=36)),
                ('bot', models.BooleanField()),
                ('state', models.IntegerField()),
                ('updatedAt', models.DateTimeField()),
            ],
        ),
    ]
