# Generated by Django 4.2.8 on 2023-12-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='threadId',
        ),
    ]
