# coding: utf-8

"""
    traQ v3

    traQ v3 API

    The version of the OpenAPI document: 3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class BotMode(str, Enum):
    """
    BOT動作モード  HTTP: HTTP Mode WebSocket: WebSocket Mode
    """

    """
    allowed enum values
    """
    HTTP = 'HTTP'
    WEBSOCKET = 'WebSocket'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BotMode from a JSON string"""
        return cls(json.loads(json_str))


